// firebase_options.dart
// This file is generated by FlutterFire CLI. Do not modify it manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

const DefaultFirebaseOptions = FirebaseOptions(
  apiKey: 'YOUR_API_KEY',
  appId: 'YOUR_APP_ID',
  messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  projectId: 'YOUR_PROJECT_ID',
  storageBucket: 'YOUR_STORAGE_BUCKET',
);
